### ISSUE TITLE
SSH Keys add button does not work

### ISSUE THREAD

**Issue by spirritus** [gitblit/gitblit#1226]
Hi,

adding ssh-keys via command line works fine, however the button on the webinterface does not seem to do anything.

**Comment by fzs** [comment]
Closing this as fixed with PR #1239, as no further feedback available. Assuming input error.

**Comment by madukan** [comment]
This issue still persist. Trying to click add after setting a ssh public key at the Gitblit profile page doesn't go anywhere. No error in the Javascript console either. I'm running through Docker, no errors seen in the Docker logs either.

**Comment by flaix** [comment]
Well, what do you see in the Docker logs? Because I just tried and it works as expected. I can add a key and after clicking add, I see the key in the list of keys.

```
2022-07-28 19:01:15 [INFO ] loading ssh keystore for florian
2022-07-28 19:02:38 [INFO ] loading ssh keystore for florian
```

**Comment by madukan** [comment]
Nothing useful in there.

2022-07-28 20:24:09 [INFO ] 23 repository models loaded for muds in 15 msecs
2022-07-28 20:24:09 [INFO ] loading ssh keystore for ****

**Comment by flaix** [comment]
But adding the SSH key via the command line works, as in the original ticket description?
Or is it that it doesn't work at all like in #1415 
I cannot reproduce this.

**Comment by flaix** [comment]
This can happen when the key cannot be parsed. Feedback in that case has been added to the web page now.
