### ISSUE TITLE
New branches only propagated by replication after a commit

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#888]
Originally reported on Google Code with ID 592

```
We are encountering what seems to us like an unexpected behavior of federation.

We have the following setup: a "master" and a "slave" gitblit instance. The slave is
kept up to date using federation.

What steps will reproduce the problem?
1. Create a new local branch on a local repository, cloned from master.
2. Push the newly created branch to master.

What is the expected output? What do you see instead?
The newly created branch can be seen on the gitblit HTML interface of the master, but
never on the slave (even after the federation delay).
As a workaround, we discovered that any commit on this new branch, when pushed on master,
would lead to the branch appearing on slave.
We would expect newly created branches to be "federated" once pushed to master, without
the need for a commit.

What version of the product are you using? On what operating system?
Both gitblit instances are v1.6.2 running under Windows Server 2008.



```

Reported by `olivier.parisy` on 2015-05-22 12:54:40

**Comment by oparisy** [comment]
Hi, a fix for this issue was originally considered for the 1.7.0 milestone.

What is its current status? May it have been fixed in an 1.7.x release?

Regards,
Olivier.

**Comment by BluAge** [comment]
Hi.
We encounter this very annoying problem, which requires us to do dummy empty commits when we make branches. These clutter our history.
The ticket is marked with "Milestone-1.7.0", but is still not fixed in 1.8, or is something not up-to-date here?
What is the ticket status?

**Comment by fzs** [comment]
@gitblit, can you remember what it was, that you saw, how that happens?
