### ISSUE TITLE
Gitblit raw now gets you too download

### ISSUE THREAD

**Issue by paladox** [gitblit/gitblit#956]
Hi when trying to view raw files at https://dev.gitblit.com/tree/gitblit.git it is telling you to download the file you carn't view it browser side.

Please change so you can view it in browser like you could in gitblit 1.4.1.

**Comment by paladox** [comment]
When viewing files such as .gitignore in raw it comes up with download.

**Comment by gitblit** [comment]
The raw servlet could probably make a guess and say dot files are plain text.  PRs welcome.

**Comment by gitblit** [comment]
Fix pushed to master.

**Comment by paladox** [comment]
Thanks.

**Comment by paladox** [comment]
Hi it still happends just that some files now work but most of the . files still have the problem such as .gitignore.

**Comment by paladox** [comment]
is dev.gitblit.org running the latest code of master branch if not ignore my comment above.
